version: '3.8'

services:
  sonarqube:
    image: sonarqube
    volumes:
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_data:/opt/sonarqube/data
    ports:
      - "8888:9000"
    
volumes:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_data: